### ISSUE TITLE
Failed to build on Ubuntu18.04

### ISSUE THREAD

**Issue by nobody93** [NTAP/quant#65]
Hi Lars,

Which branch I should use, master?

Which files involve to support Full-cone NAT?

I followed the build document to build it on Ubuntu 18.04 laptop, here is an error: 

-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found suitable version "1.1.1", minimum required is "1.1.0")

So, I have  libssl-dev:amd 1.1.1-1ubunt amd64  installed, there are a couple of errors in CMakeError.log:

CheckSymbolExists.cxx:2:10: fatal error: benchmark/benchmark.h: No such file or directory
 #include <benchmark/benchmark.h>
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

CheckIncludeFile.c:1:10: fatal error: net/netmap_user.h: No such file or directory
 #include <net/netmap_user.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
CheckSymbolExists.c:2:10: fatal error: gperftools/profiler.h: No such file or directory
 #include <gperftools/profiler.h>
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Sorry, am I still missing some libraries?

Thank you very much.

jupiter

**Comment by larseggert** [comment]
Yes, you should use `master`.

No, you are not missing libraries. You can ignore these errors. Does quant not build?

**Comment by larseggert** [comment]
@nobody93 is it working for you? Can I close this?

**Comment by nobody93** [comment]
Hi Lars,

Thanks for your response, it did not work, the cmake quant did not generate the Makefile, it stopped at above error message. Let me know if you need more information.

Thank you.

Jupiter

**Comment by larseggert** [comment]
You need to please post the exact commands you type together with the generated output.

**Comment by nobody93** [comment]
Hi Lars,

Here are the commands and output:
$ ls
Debug quant

$ cd Debug

$ cmake ../quant/
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for benchmark::Initialize
-- Looking for benchmark::Initialize - not found
-- Looking for net/netmap_user.h
-- Looking for net/netmap_user.h - not found
-- Looking for ProfilerStart
-- Looking for ProfilerStart - not found
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found suitable version "1.1.1", minimum required is "1.1.0") 
CMake Error at CMakeLists.txt:46 (add_compile_definitions):
  Unknown CMake command "add_compile_definitions".

Let me know if you need more information.

Thank you.

Jupiter

**Comment by nobody93** [comment]
Hi Lars, any advice?

**Comment by larseggert** [comment]
What version is your cmake (run `cmake --version`). My guess is it's too old.

**Comment by nobody93** [comment]
$ cmake --version
cmake version 3.10.2

**Comment by larseggert** [comment]
I think at least 3.12 or so. If you pull from master and try to build, it should tell you now.

**Comment by larseggert** [comment]
@nobody93 is it building now?

**Comment by larseggert** [comment]
No answer, closing this for now.
